name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: 0-vortex/workflow-reusability-test/.github/workflows/open-sauced-compliance.yml@main
